# _config.yml
title: "8Sec"
description: "Application Security as a Service (AppSec-as-a-Service) for startups and SMBs."
url: "https://eightsec.com"        # e.g., https://eightsec.com or https://qaztiel.github.io
baseurl: ""                         # "" for root domain; "/8sec" if it’s a project site
permalink: pretty

# If you use jekyll-seo-tag, keep these clean:
author: 8Sec

# plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
- README.md
- Gemfile
- Gemfile.lock